# NOTE:

This is a stencil for TFIDF assignment to help you understand the flow and code along.

If you like my work show some love by endorsing/reccomending me on Linkedin in python/datascience/management. [mayur-kagathara](https://www.linkedin.com/in/mayur-kagathara/)

In [2]:
# Corpus to be used for this assignment
import numpy as np
corpus = [
     'this is the first document mostly',
     'this document is the second document',
     'and this is the third one',
     'is this the first document here',
]

In [9]:
#create set of words in corpus
#1. create empty set sow as set()
sow=set()

#for all sentence in corpus add word into sow. Two for loops can be used to get word out of corpus
#1. first for loop to get sent
#2. second for loop to get words from sent.split()
for sent in corpus:
    for word in sent.split():
        sow.add(word)

#save sow in list sow sow=list(sow)
sow=list(sow)
print(sow)
# OUTPUT - ['here', 'is', 'third', 'the', 'one', 'first', 'second', 'this', 'document', 'mostly', 'and']

['here', 'is', 'third', 'the', 'one', 'first', 'second', 'this', 'document', 'mostly', 'and']


In [13]:
#for each word in SOW count the number of sentences containing the word
#for example, count for document is 3

#create empty idf_count_dict using sow list
idf_count_dict = dict.fromkeys(sow,0)
#use for loop to get word out of sow
#use nested for loop to get sent out of corpus.
#Check if word is inside sentence, if yes than increase the count by 1.
# add this count in dictionary idf_count_dict
for word in sow:
    count = 0
    for sent in corpus:
        if word in sent:
            count += 1
    idf_count_dict[word] = count

print(idf_count_dict)
#OUTPUT - {'here': 1, 'is': 4, 'third': 1, 'the': 4, 'one': 1, 'first': 2, 'second': 1, 'this': 4, 'document': 3, 'mostly': 1, 'and': 1}

{'here': 1, 'is': 4, 'third': 1, 'the': 4, 'one': 1, 'first': 2, 'second': 1, 'this': 4, 'document': 3, 'mostly': 1, 'and': 1}


In [17]:
# Calculate IDF value using idf_count_dict
idf_dic = dict.fromkeys(sow,0)

# Loop through key (word) and value (count) in idf_count_dict
# calculate IDF_Value and update it into idf_dic

for word,count in idf_count_dict.items():
    idf_val = np.log(4/count)
    idf_dic[word] = idf_val

print(idf_dic)
#OUTPUT - {'here': 1.3862943611198906, 'is': 0.0, 'third': 1.3862943611198906, 'the': 0.0, 'one': 1.3862943611198906, 'first': 0.6931471805599453, 'second': 1.3862943611198906, 'this': 0.0, 'document': 0.28768207245178085, 'mostly': 1.3862943611198906, 'and': 1.3862943611198906}

{'here': 1.3862943611198906, 'is': 0.0, 'third': 1.3862943611198906, 'the': 0.0, 'one': 1.3862943611198906, 'first': 0.6931471805599453, 'second': 1.3862943611198906, 'this': 0.0, 'document': 0.28768207245178085, 'mostly': 1.3862943611198906, 'and': 1.3862943611198906}


In [20]:
#declare empty list TFIDF
TFIDF = []

for sent in corpus:
    total_words = len(sent.split())
    tfidf_temp_list = []
    for word in sent.split():
        word_count = sent.count(word)
        tf = word_count/total_words
        tfidf_val = tf * idf_dic[word]
        tfidf_temp_list.append(round(tfidf_val,2))
    TFIDF.append(tfidf_temp_list)

TFIDF = np.array(TFIDF)
print(TFIDF)
# OUTPUT - 
# [[0.   0.   0.   0.12 0.05 0.23]
#  [0.   0.1  0.   0.   0.23 0.1 ]
#  [0.23 0.   0.   0.   0.23 0.23]
#  [0.   0.   0.   0.12 0.05 0.23]]

[[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]


## Now your task is to compile everything in below function

In [61]:
def computeTFIDF (corpus):
  ##############################################################
  ####   YOUR CODE BELOW  as per the above instructions #######
  ##############################################################

# Grader Cell
Please execute the following Grader cell to verify the correctness of your above implementation. This cell will print "Success" if your implmentation of the computeTFIDF() is correct, else, it will print "Failed". Make sure you get a "Success" before you submit the code in the classroom.

In [62]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the computeTFIDF() is correct.
# Else, it will print "Failed"
###########################################
import numpy as np

# compute TF-IDF using the computeTFIDF() function
X_custom = computeTFIDF(corpus)

# Reference grader array - DO NOT MODIFY IT
X_grader = np.array(
    [[0, 0, 0, 0.12, 0.05, 0.23],
     [0, 0.1, 0, 0, 0.23, 0.1],
     [0.23, 0, 0, 0, 0.23, 0.23],
     [0, 0, 0, 0.12, 0.05, 0.23]]
     )

# compare X_grader and X_custom
comparison = ( X_grader == X_custom )
isEqual = comparison.all()

if isEqual:
  print("******** Success ********")
else:
  print("####### Failed #######")
  print("\nX_grader = \n\n", X_grader)
  print("\n","*"*50)
  print("\nX_custom = \n\n", X_custom)


******** Success ********
